### PR TITLE
Add check for warning about user-defined sensitive access

### PR DESCRIPTION
**Pull request by xen0l**
This PR adds community auditor that takes user-provided config values and checks policies for presence of sensitive action/resource. 

Some hilights:
* policy object now takes config as an argument when instantiating the object. This allows to pass in config contents to check itself
* I removed unused imports

### CODE REVIEW

**Comment by xen0l** [comment]
@0xdabbad00 any comments?

**Comment by xen0l** [comment]
@0xdabbad00 any feedback?

**Comment by 0xdabbad00** [comment]
Sorry for the delays. LGTM. Thank you @xen0l .  I want to test it and add a unit test for a negative test case and also have multiple action and resource values checked.

**Comment by 0xdabbad00** [comment]
I've added some more unit tests to this in #123.  I don't believe it is possible for me to add commits to someone else's PR, so I've created the new PR and am closing this one so that one can be merged. You'll still end up in the commit history @xen0l .

**Pull request closed without merging**
