### PR TITLE
resource_star: only report the offending actions after expansion

### PR DESCRIPTION
**Pull request by dgubitosi**
This is for discussion regarding Issue https://github.com/duo-labs/parliament/issues/117

This code produces the following output for your example policy using ec2:Create*

`RESOURCE_STAR - None - {'actions': ['ec2:CreateClientVpnEndpoint', 'ec2:CreateClientVpnRoute', 'ec2:CreateFlowLogs', 'ec2:CreateLaunchTemplateVersion', 'ec2:CreateLocalGatewayRoute', 'ec2:CreateLocalGatewayRouteTableVpcAssociation', 'ec2:CreateNetworkInterfacePermission', 'ec2:CreateRoute', 'ec2:CreateSnapshot', 'ec2:CreateSnapshots', 'ec2:CreateTrafficMirrorFilter', 'ec2:CreateTrafficMirrorFilterRule', 'ec2:CreateTrafficMirrorSession', 'ec2:CreateTrafficMirrorTarget', 'ec2:CreateTransitGateway', 'ec2:CreateTransitGatewayMulticastDomain', 'ec2:CreateTransitGatewayPeeringAttachment', 'ec2:CreateTransitGatewayRoute', 'ec2:CreateTransitGatewayRouteTable', 'ec2:CreateTransitGatewayVpcAttachment', 'ec2:CreateVolume', 'ec2:CreateVpcEndpoint', 'ec2:CreateVpcEndpointServiceConfiguration', 'ec2:CreateVpcPeeringConnection', 'ec2:CreateVpnConnection'], 'filepath': None}`

What caught me by surprise is that the expanded_actions list contains duplicates.  I haven't looked into why yet and have instead worked around it by using a dict to squash the duplicates.  If I dump the actual dict from above, you'll see the count of each action:

`RESOURCE_STAR - None - {'actions': {'ec2:CreateTransitGatewayRouteTable': 2, 'ec2:CreateTrafficMirrorFilter': 1, 'ec2:CreateVpnConnection': 1, 'ec2:CreateVpcEndpoint': 2, 'ec2:CreateLocalGatewayRoute': 2, 'ec2:CreateRoute': 1, 'ec2:CreateSnapshots': 3, 'ec2:CreateVpcEndpointServiceConfiguration': 1, 'ec2:CreateTrafficMirrorTarget': 1, 'ec2:CreateLocalGatewayRouteTableVpcAssociation': 2, 'ec2:CreateClientVpnRoute': 2, 'ec2:CreateTransitGatewayRoute': 1, 'ec2:CreateVpcPeeringConnection': 2, 'ec2:CreateTrafficMirrorSession': 4, 'ec2:CreateTransitGateway': 1, 'ec2:CreateTransitGatewayVpcAttachment': 3, 'ec2:CreateClientVpnEndpoint': 1, 'ec2:CreateTrafficMirrorFilterRule': 2, 'ec2:CreateLaunchTemplateVersion': 1, 'ec2:CreateSnapshot': 2, 'ec2:CreateTransitGatewayPeeringAttachment': 2, 'ec2:CreateNetworkInterfacePermission': 1, 'ec2:CreateTransitGatewayMulticastDomain': 2, 'ec2:CreateVolume': 1, 'ec2:CreateFlowLogs': 1}, 'filepath': None}`

### CODE REVIEW

**Comment by dgubitosi** [comment]
The duplicates come from iterating over the list of resource types for each action in the expanded list.  This makes sense.

**Comment by 0xdabbad00** [comment]
Thank you @dgubitosi

**Comment by dgubitosi** [comment]
No discussion?  :)

**Comment by 0xdabbad00** [comment]
Looked good to me.

**Pull request merged**
