### PR TITLE
Fixes #74, get-account-authorization-details file support

### LINKED ISSUE #74: get-account-authorization-details file analysis is not working
I put together a gist to help reproduce, with a sanitized example json file.

https://gist.github.com/kmcquade/a809fff851371ffffe7bdb70bf5e1965

Command:
```
parliament --auth-details-file example-get-account-authorization-details.json --private_auditors tmp/parliament_auditors
```

Response:

```
Traceback (most recent call last):
  File "/Users/kmcquade/Library/Python/3.7/bin/parliament", line 8, in <module>
    sys.exit(main())
  File "/Users/kmcquade/Library/Python/3.7/lib/python/site-packages/parliament/cli.py", line 180, in main
    json.dumps(version["Document"]), role["Arn"], private_auditors_custom_path=args.private_auditors
UnboundLocalError: local variable 'version' referenced before assignment
```

I made a fix for the issues in handling that file, so I will make a PR shortly.

### PR DESCRIPTION
**Pull request by kmcquade**

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
I'm not sure about ignoring the AWS Service-linked roles, because any bad policy being used should be fixed. If it is a policy from AWS, then we should get AWS to fix the policy.  What are your thoughts?

**Comment by kmcquade** [comment]
That's true. But I think this could be accomplished without the use of the get-account-authorization-details output. We don't want to generate a *ton* of false positives for Parliament users who just want to view what they have control of in their account.

**Comment by 0xdabbad00** [comment]
Good point. I assume the policies you've filtered can only be used by AWS? I'll take a look at this again later tonight.

**Comment by kmcquade** [comment]
I believe so.

**Comment by jplock** [comment]
I thought aws-service-role was reserved for their use but service-role anyone can use?

**Pull request merged**
