### PR TITLE
chore: update iam_definition on 2024-03-13

### PR DESCRIPTION
**Pull request by ChrisTowles**
Ran the update script with a few improvements to give feedback while it runs.

image

Feedback welcome

### CODE REVIEW

**Comment by zuBux** [comment]
hey folks! Any chance you can merge this and create a new release. `parliament` has been complaining lately about new AWS permissions and I'm pretty sure this will fix the issue

**Comment by artem-smotrakov** [comment]
Hey friends! When you get some time, I'd appreciate it if you could merge and release this change. Thanks!

@ChrisTowles Thanks for the PR!

**Comment by zuBux** [comment]
Thanks @rjcassara- , would it be possible to create a new release? It's a lot easier to reference a new version number in our dependencies :D

**Comment by iainelder** [comment]
@zuBux , [version 1.63](https://github.com/duo-labs/parliament/releases/tag/1.63) just released today with these changes.

**Pull request merged**
