### PR TITLE
Fixes #7

### LINKED ISSUE #7: Validate Statement Id values
If set, the `Sid` field in IAM policies may only contain characters from `(A-Z,a-z,0-9)`. `parliament` should declare a finding if `Sid` has spaces or other invalid characters.

### PR DESCRIPTION
**Pull request by santoshankr**
If `Sid` is set, check it matches the regex `[0-9A-Za-z]*`

### CODE REVIEW

**Comment by 0xdabbad00** [comment]
Thank you @santoshankr !

**Comment by danielpops** [comment]
FYI the sid regex in this PR is correct for IAM policy, but each amazonaws service that has resource-based policies could have differing validation on the sid (e.g. s3)

From https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_grammar.html
```
sid_string
Provides a way to include information about an individual statement. For IAM policies, basic alphanumeric characters (A-Z,a-z,0-9) are the only allowed characters in the Sid value. Other AWS services that support resource policies may have other requirements for the Sid value. For example, some services require this value to be unique within an AWS account, and some services allow additional characters such as spaces in the Sid value.
```

**Comment by santoshankr** [comment]
Hrm, I made the assumption that this only covered IAM policies. Resource-based policies differ in a few other ways too, don't they? For example, you can't have a `Principal` block in a resource-based policy. I think the correct fix is to have a common set of constraints checked in the base `Policy` class, but move anything IAM specific to an `IAMPolicy` subclass. We'll also need an API change so users can tell us whether they're passing in an IAM policy or a resource-based one so we can check the appropriate constraints.

**Comment by 0xdabbad00** [comment]
I did make Parliament primarily for IAM policies, but given that Resource based policies are so similar, I did try to cover them as well. So for example, if there is a `Principal` in the statement, then it will be checked to ensure it conforms to an expected format: https://github.com/duo-labs/parliament/blob/a36fc08392d5c50c6742812fe5427d8d00c55fb8/parliament/statement.py#L367

This does however mean that if you have an IAM policy with a `Principal` element (which would be incorrect), that Parliament will not complain.  As @santoshankr mentioned, it seems the best path forward to account for these differences would be to have Parliament told the type of policy it is checking (IAM or Resource, and potentially what kind of resource policy).  I've ticketed this as #14.

**Pull request merged**
